### ISSUE TITLE
Audio no longer plays 8.4

### ISSUE THREAD

**Issue by Maverynthia** [FelicitusNeko/FlixelBumpStik#7]
The audio doesn't play in the new 8.4 version.

**Comment by FelicitusNeko** [comment]
The game might possibly be muted. Try pressing either 0 key on the keyboard. This is Flixel system behaviour.

**Comment by Maverynthia** [comment]
OK that made it work. Thanks. 
I think what happened was when I was typing in the AP port it had a 0 in it.

**Comment by FelicitusNeko** [comment]
I may have to remove or replace the default Flixel volume changer because of this. I don't know if I can just temporarily disable it. For 0.9.0, I can probably just get rid of it, at least temporarily.
